# Generated by Django 5.1.2 on 2024-10-25 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cartitem_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 25, 13, 58, 7, 966070)),
        ),
    ]
